#!/bin/zsh
set -euo pipefail

# Builds the GrimoraEngineApp dashboard ("Grimora Engine") in Release and installs it into
# /Applications, so it becomes a permanent, Spotlight-searchable program with a menu-bar tray
# icon. This is a local developer tool — it is intentionally separate from the App Store
# `release` skill (which ships GrimoraMac/iOS/VisionOS, not the engine app) and needs no
# notarization for personal use.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCHEME="GrimoraEngineApp"
APP_NAME="Grimora Engine.app"
INSTALL_DIR="/Applications"
BUILD_DIR="$(mktemp -d)/GrimoraEngineApp"

cd "$ROOT_DIR"

# project.yml is the source of truth; Grimora.xcodeproj is gitignored and regenerated by XcodeGen.
if command -v xcodegen >/dev/null 2>&1; then
  xcodegen generate
fi

xcodebuild \
  -project Grimora.xcodeproj \
  -scheme "$SCHEME" \
  -configuration Release \
  -derivedDataPath "$BUILD_DIR" \
  build

APP_PATH="$BUILD_DIR/Build/Products/Release/$APP_NAME"
if [[ ! -d "$APP_PATH" ]]; then
  echo "Build did not produce $APP_PATH" >&2
  exit 1
fi

# Replace any previous install with the fresh build.
rm -rf "$INSTALL_DIR/$APP_NAME"
cp -R "$APP_PATH" "$INSTALL_DIR/$APP_NAME"

# Force Spotlight to index the new app immediately so searching "Grimora" finds it right away.
mdimport "$INSTALL_DIR/$APP_NAME" || true

echo "Installed $INSTALL_DIR/$APP_NAME"
open "$INSTALL_DIR/$APP_NAME"
